

            
# -*- coding: utf-8 -*-
"""decryption

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_eQx1Vzt85fPMX1AZdd0idBJWaLG01Y
"""

def decrypt(shift1, shift2):

    with open("encrypted_text.txt", "r") as f:
        encrypted = f.read()

    result = []
    for ch in encrypted:
        if ch.isupper():
            idx = ord(ch) - ord('A')
            if idx <= 12:
# Reversing A-M rule by add shift1
                new_idx = (idx + shift1) % 26
            else:
# Reversing N-Z rule by subtract shift2^2
                new_idx = (idx - shift2 ** 2) % 26
            result.append(chr(new_idx + ord('A')))

        elif ch.islower():
            idx = ord(ch) - ord('a')
            if idx <= 12:
 # Reversing of a-m rule by subtract shift1*shift2
                new_idx = (idx - shift1 * shift2) % 26
            else:
 # Reversing of n-z rule by add shift1 + shift2
                new_idx = (idx + (shift1 + shift2)) % 26
            result.append(chr(new_idx + ord('a')))

        else:
            result.append(ch)

    with open("decrypted_text.txt", "w") as f:
        f.write(''.join(result))

    print("Decryption complete  ->  decrypted_text.txt")
